### ISSUE TITLE
モデルの性能検証

### ISSUE THREAD

**Issue by Prokuma** [Kyutech-C3/EmoMee-frontend#5]
face-api.jsが提供している顔検出のモデルは合わせて三つある。
その三つの性能検証を行う。

## 検証対象モデル
- TinyFaceDetector: 最も軽い(KB単位)
- MTCNN: 2番目に軽い(2MB程度)
- SSD Mobilenet V1: 一番重い(5MB程度)

予想では精度はモデルの大きさに比例
速度はモデルの軽さに比例

## やるべきこと
- それぞれのモデルの検証用のブランチを作成
- それぞれのコードを作成し、プッシュ
- 各ブランチにおいて性能検証を行う

## 役割分担
- Prokuma: ブランチ・コード作成
- Cat・シモ: 性能検証

**Comment by catgolem** [comment]
### **・検証結果**
・ MTCNN

**Comment by Simo-C3** [comment]
・動作環境
Ryzen 5 3600
RAM 32GB
タブ　20個以上存在する状態

・TinyFaceDetector
読み込み速度：一番早い。待たされている感じはあまりない。
精度：微妙。誤判定が目立つ。

・MTCNN
読み込み速度：多少待たされている感じがある。
精度：まし。それなりにいい感じに判定している感じがある。

・SSD Mobilenet
読み込み速度：遅め。多少待たされている感じがある。MTCNNに比べて少し遅い感じがする程度
精度：一番いい。横を向いたときでも拾ってくれる。

・意見
初回のロード時間が長いがそれ以降はロードをしないので、SSD Mobilenetを使ってもいいと思う。

**Comment by Prokuma** [comment]
@catgolem どちらを採用した方がいいかの意見が欲しい

**Comment by catgolem** [comment]
@Prokuma 
シモの奴とは体感異なったんですけど，SSD MobilenetがMTCNNに比べて早く感じたし，マスクありの場合での読み込みがまともだったので，SSD Mobilenetを押します．
もしくは，モード変更という機能を設定画面で追加して，「軽いモード：TinyFaceDetector」，「重いモード：SSD Mobilenet」で選択できるようにしてもいいかもしれません．

**Comment by Prokuma** [comment]
@Simo-C3 @catgolem SSD Mobilenet V1を採用することにしました。プルリク投げたので確認後マージお願いします。
